### ISSUE TITLE
US51 - Fórum

### ISSUE THREAD

**Issue by marimendes** [fga-gpp-mds/2018.1-Dr-Down#101]
Eu, como usuário, cadastrado gostaria de acessar o fórum a fim de ler ou fazer uma postagem.

Eu, como visitante do site, gostaria APENAS de ler os posts do fórum.

-  Qualquer usuário pode ler o fórum
-  Para comentar no fórum o usuário precisa ser cadastrado
-  O post precisa de assunto
-  Categorias predefinidas 
-  Criar um grupo moderador
-  O usuário cadastrado pode postar, editar e deletar(Ele só pode deletar o próprio post e editar também).
- O usuário cadastrado pode comentar, editar o comentário e deletar(se for o comentário dele)
- Precisa de hora e data da postagem.

**Comment by GeovanaRamos** [comment]
"O post precisa de assunto": com isso você quer dizer que o post tem um atributo "assunto"/"título" ou que eles pertecem à um assunto?

**Comment by marimendes** [comment]
O post tem um atributo assunto para que o usuário consiga filtrar os posts pelo assunto.

**Comment by Diego-BF** [comment]
Essa pergunta me gerou uma dúvida: um post pode ter vários assuntos ou apenas 1?

**Comment by GeovanaRamos** [comment]
Acho que considerando a resposta da Mariana , isso não vem ao caso (se estiver pensando em relacionamentos de classe), pois o assunto trata-se apenas de um título do post e não uma classe com relacionamentos. Resumindo: o assunto é o título charfield dado ao post e , portanto, podem existir inúmeros.

**Comment by VictorArnaud** [comment]
Galera encontrei um microserviço de forum muito bom, executem ele e tente adaptar ao nosso projeto

https://github.com/urtzai/django-forum-app
