### ISSUE TITLE
Feedback 02

### ISSUE THREAD

**Issue by RochaCarla** [fga-gpp-mds/2018.1-Dr-Down#110]
- [x] Somente  o Victor presente na aula

- [x] Melhorar readme

- [x] não tem o entrega continua (travis doc) 

- [x] EAP descreve o projeto, não entregas de valores para o cliente 

- [x] Arquitetura ruim -- não é microsserviços

- [x] Risco - não entregar arquitetura microsserviços é um grande problema para R1 (má gestão de riscos)

- [x] Falta uma melhor definição de produto para guiar o projeto

**Comment by sconetto** [comment]
@RochaCarla,
Boa tarde, gostaria de pontuar algumas questões sober o que você levantou nessa _issue_:

- A entrega contínua (deploy contínuo) foi planejado para ser entregue na sprint passada, mas devido a alguns problemas enfrentados, conforme levantado pelas _issues_ #83 #60, não conseguimos entregar a história, o que foi até conversado com você pessoalmente, pois estavamos com problema de falta de algum host para continuar a implementação da história, você, quando eu a procurei em aula, me instruiu a procurar o cliente (Sanderson do CDT), pois ele poderia ceder um host para que pudessemos continuar com o CD, mas neste contato também tivemos problemas, o cliente expressou vontade em realizar reunião presencial no CDT as sextas, mas todos os membros de EPS, sem exceção, cumprem carga horária de estágio no período contrário ao da UnB, com isso foi acordado realizar reuniões não presenciais (via Hangout), mas o **mesmo se ausentou em todas as reuniões marcadas**, alegando problemas pessoais ou de agenda profissional, ou até mesmo não explanando o motivo da ausência, foi levantado então a possibilidade do mesmo participar das reuniões semanais da equipe que ocorrem no gama, e novamente, o mesmo se mostrou inviável ao cliente, desta forma não foi possível fazer o que foi solicitado. Atualmente estamos "correndo atrás" do plano B que consistirá na compra de um cartão pré-pago internacional para custear as despesas iniciais do host, está sendo levantado com a equipe fundos para essa aquisição, mas até o fim de alguns trâmites estamos impossibilitados de fazer o CD.  

- Gostaria de pedir uma complementação no ponto de faltar melhor definição do produto para guiar o projeto, pois adicionado ao problema que temos de comunicação com o cliente, acreditamos que o produto está definido com o que foi documentado pelo equipe e com a referência que nos foi passada, desta maneira, estavamos nos guiando e planejando a partir disso, então caso tenha algum input sobre o projeto para nós quero solicitar a presteza de documentar aqui para que possamos incluir no projeto (é necessário documentar um backlog do produto?).

**Comment by Diego-BF** [comment]
@RochaCarla , quanto ao risco da arquitetura, ela não havia sido incluído previamente pois quando o nosso grupo falou dela com você anteriormente, não haviam sido apontado problemas. Mas ele será incluído nessa sprint e terá o devido acompanhamento e gerenciamento de agora em diante.
