### ISSUE TITLE
TS24 - Elaboração do Documento de Arquitetura

### ISSUE THREAD

**Issue by marimendes** [fga-gpp-mds/2018.1-Dr-Down#12]

**Comment by VictorArnaud** [comment]
Galera vou mandar um link de alguns tutoriais para vocês seguirem e criarem o doc de arquitetura: https://drive.google.com/open?id=1jFPLyEIQS5v6Xn4W68C2bY4EBOlQ5tt1 e qualquer duvida estou a disposição ou na S9 ou no ITRAC
