### ISSUE TITLE
TS59 - Refatorar usuário base

### ISSUE THREAD

**Issue by marimendes** [fga-gpp-mds/2018.1-Dr-Down#132]
- Passar o botão do sign in e o sign up pra lado direito. 
- A cor do link sign in é muito claro. 
- Quando for a primeira vez que o usuário se cadastrar levar pra página de confirmar os dados.
- Traduzir
- Trocar a cor dos botões

**Comment by gabiMSilva** [comment]
* Máscara para o campo de telefone e CPF
