### ISSUE TITLE
TS62 - Inconsistência na especialização do usuário

### ISSUE THREAD

**Issue by marimendes** [fga-gpp-mds/2018.1-Dr-Down#135]
Concertar bug na especialização do usuário.

**Comment by ebmm01** [comment]
**Sobre o que fizemos:**

Precisávamos impedir a múltipla especialização de um usuário em todas as models. Pra resolver isso nós adicionamos um novo atributo na *model_user* que é um bool falso por padrão, um contador inicializado em 0 que continua 0 se o user base não tem especializações e aumenta 1 pra cada especialização (mas isso não vai ocorrer). E sobrescrevemos o método def clean() que é um validador do django: ele checa o contador citado anteriormente e atribui falso pro bool se ele for 0, true se for 1 e erro se >1.

Nas models especializadas adicionamos um post_delete (na verdade foi o Sconetto) que após uma especialização ser deletada ele seta o user base dessa especialização pra ter o valor de *has_specialization* (o bool que adicionamos) de volta pra False.

**O que deveria acontecer:**

Ao criar um usuário especializado o has_specializations vai para True. Ao deletá-lo o has_specializations deveria voltar para False.

**O que está acontecendo:**

Está inconsistente então vamos por model:

Na doctor ele muda o has_specialization para True na criação mas não volta pra False na deleção.
Na employee ele muda o has_specialization para True na criação mas não volta pra False na deleção.
Na patient e no responsible ele NÃO muda o has_specialization para True na criação, o que faz o user ainda ser listado como possível usuário a ser especializado. Porém se você tentar reespecializar esse user você não consegue ( o que é um bom sinal). Ao excluir o bool continua falso mas você pode especializar o user base novamente (ou seja, comportamento correto).

**O que deve ser alterado:**

Doctor & employee: fazer o bool ir para false na deleção.
Patient & Responsible: fazer o bool ir para true na criação.

**Observações:**

~Doctor & employee tiveram o método delete sobrescrito, mas o Patient & Responsible não. Isso é algo que pode indicar o caminho por onde ir.~

update:consegui fazer model Patient e Responsible setarem o  bool pra True, mas eles não retornam pra false na exclusão (estão iguais doctor e employee agora). Pra fazer isso é só adicionar
