### ISSUE TITLE
US70 - Prontuário

### ISSUE THREAD

**Issue by marimendes** [fga-gpp-mds/2018.1-Dr-Down#161]
Eu, como médico, gostaria de criar o prontuário a fim de acompanhar melhor meu paciente.

Eu, como médico, gostaria de editar o prontuário a fim de corrigi-lo ou melhora-lo.

Eu, como médico, gostaria de excluir o prontuário.

Eu, como médico, gostaria de pesquisar e ver os prontuários para facilitar meu trabalho.

**Comment by marimendes** [comment]
Campos: Dia, hora, autor (membro da equipe médica), texto

**Comment by VictorArnaud** [comment]
Componente para pesquisa e filtros: https://github.com/gregplaysguitar/django-simple-search

**Comment by VictorArnaud** [comment]
Componente para pesquisa e filtros usando Class Based Views: https://github.com/inmagik/django-search-views

**Comment by marimendes** [comment]
@ebmm01 Pode sim, acredito que na pesquisa o médico ou funcionário não irá pesquisar pela hora, apenas pelo dia.

**Comment by marimendes** [comment]
@ebmm01  @joberthrogers18 Critérios de aceitação: 

- Precisa ser testado;
- Precisa ser traduzido;
- O médico deve ser capaz de pesquisar por dia, autor e paciente.
- Quando for listar o resultado da pesquisa, em caso de aparecer mais de um, fazer uma ordenação.
EX: se no mesmo dia foram feitos 10 prontuários, eles devem ser listado com base na hora. 
- A paginação da página de resultados deve ser 10. (Caso 10 seja pouco, pode ser de 15)
