### ISSUE TITLE
US71 - Checklist

### ISSUE THREAD

**Issue by marimendes** [fga-gpp-mds/2018.1-Dr-Down#162]
Eu, como paciente, gostaria de acessar o meu checklist a fim de conhecimento sobre as minhas vacinas e procedimentos médicos

Eu, como responsável, gostaria de marcar no checklist de acordo com a minha idade a fim de informar a equipe médica.

Eu, como paciente e ou responsável, gostaria de ser notificado sobre o meu checklist.

**Comment by marimendes** [comment]
Os dados sobre o checklist estão todos no nosso drive;

**Comment by VictorArnaud** [comment]
Componentes de notificação:
- Sem duvida o melhor e mais completo: https://github.com/pinax/pinax-notifications/
- Esse disponibiliza de um frontend bem interessante: https://github.com/areski/django-frontend-notification
- Notificações mais voltadas ao django admin: https://github.com/alireza-molaee/django-webline-notifications

**Comment by marimendes** [comment]
Critérios de aceitação:

- Deve ser testado;
- Deve ser traduzido;
- Os checklist devem aparecer de acordo com a idade do paciente.
- Se o paciente tiver menos de 13 anos, ou seja, em todos os casos já que o checklist vai de RN a 10 anos, o responsável deve ser aquele a preencher o checklist.
