### ISSUE TITLE
US78 - Consulta

### ISSUE THREAD

**Issue by marimendes** [fga-gpp-mds/2018.1-Dr-Down#186]
Eu, como funcionário, gostaria de criar um consulta para o paciente e/ou responsável.

Precisa criar, listar, deletar(cancelar a consulta) e editar. 

Campos: turno, hora, data, motivo, especialidade, equipe de sáude, status (consulta agendada, cancelada ou "já realizada" - caso a consulta já tenha ocorrido)
Os campos obrigatórios são: turno, data, hora, especialidade.
O status não será colocado na criação.

O paciente ou/e responsável devem ser notificados de acordo com o status da consulta (Para os 3 casos)

O paciente e responsável só podem ver as suas consultas.

A equipe de saúde só pode ver as consultas relacionadas a ele.

Apenas o funcionário consegue ver todas as consultas. 
 
Além do crud é necessário um campo de pesquisa pro funcionário e a equipe médica pesquisarem suas consultas.

Os campos de busca são dia, especialidade, equipe médica e paciente.

**Comment by VictorArnaud** [comment]
Componente de agenda: https://github.com/llazzaro/django-scheduler

**Comment by VictorArnaud** [comment]
Componente de  notificação: https://github.com/pinax/pinax-notifications/

**Comment by GeovanaRamos** [comment]
A agenda não é uma outra feature/issue?

**Comment by marimendes** [comment]
@GeovanaRamos Sim
