### ISSUE TITLE
US80 - Ficha de acompanhamento.

### ISSUE THREAD

**Issue by marimendes** [fga-gpp-mds/2018.1-Dr-Down#188]
Unir as funcionalidades referentes ao ficha de acompanhamento (prontuário e checklist)

**Comment by marimendes** [comment]
![photo5130057871084595189](https://user-images.githubusercontent.com/11450196/39408361-682be87a-4bab-11e8-93d1-4537ae057b95.jpg)

**Comment by VictorArnaud** [comment]
Componente para utilização de PDFs: https://pypi.org/project/reportlab/
