### ISSUE TITLE
Problemas com o Travis CI

### ISSUE THREAD

**Issue by sconetto** [fga-gpp-mds/2018.1-Dr-Down#197]
O travis ci não está executando os passos como deveria executar.

## Comportamento Esperado
Ele deveria fazer o tag da última imagem buildada e pushar para o repositório no docker hub, para que na máquina host ela pudesse dar o pull nessa imagem e substituir a versão antiga, com isso garantindo o deploy contínuo.

## Comportamento Atual
Ele não consegue fazer o login no docker, nem o tag e com isso cascateia diversos problemas no deploy contínuo.

## Possível Solução
Sem ideias de possíveis soluções, já que em máquina local tudo funciona como deveria.

## Passos para Reproduzir (para bugs)
Os passos executados que geram os erros estão dentro do script de deploy:
https://github.com/fga-gpp-mds/2018.1-Dr-Down/blob/develop/staging-deploy.sh

## Contexto
Com isto o deploy contínuo fica comprometido

## Seu Ambiente
* Versão usada (Software): versão mais atual do repositório do Dr. Down
* Nome e versão do navegador: Não se aplica
* Nome e versão do Sistema Operacional (desktop ou mobile): Ubuntu 17.10 (pessoal) - Ubuntu 16.04.4 LTS (host)

OBS: O comportamento pode ser observado nas jobs do travis-ci a partir da linha 2013
https://travis-ci.org/fga-gpp-mds/2018.1-Dr-Down/builds/373450397#L1255

**Comment by VictorArnaud** [comment]
Problema com mapeamento de porta: dentro da pasta /etc/nginx/nginx.conf tem um arquivo de configuração do nginx que import arquivos da pasta sites-enable, dentro dessa pasta tem um arquivo chamado default com o servidor padrão do nginx na porta 80 aquele que aparece a mensagem Welcome to nginx! com isso modifiquei o atributo da porta do servidor para 800 para não dar conflito com nosso projeto que está na porta 80 ;)
