### ISSUE TITLE
US83 - Evoluir prontuário

### ISSUE THREAD

**Issue by sconetto** [fga-gpp-mds/2018.1-Dr-Down#204]

**Comment by guilherme1guy** [comment]
![image](https://user-images.githubusercontent.com/7153715/39673405-0252ddda-5112-11e8-95fa-7f8b20d95034.png)

**Comment by marimendes** [comment]
**ABA 1** 
1- Prontuário:Nome Completo (variável string)
Sexo: Masculino / Feminino (variável categórica)
Data de Nascimento: (variável data)
SES

**ABA 2**
Isso daqui é feito uma vez só, então pro médico não precisar colocar toda vez no prontuário.
Peso ao Nascer: (número)
APGAR: (número de 1 a 10)
Teste do Coraçãozinho: (upload)
Teste da Orelhinha: (upload)

**ABA 3**
Medicamentos em uso: text
nome do medicamento, dosagem.

**ABA 4**
(Todos esses campos são uploads)
Exame Físico Estruturado:
Visão:
Audição:
Coração:
Sistema músculo esquelético:
Sistema nervoso:

**ABA 5**
Queixa: data, descrição, hora, equipe médica responsável.

**ABA 6**
Exames: Nome do exame, data do exame, horário, status(executado, colhido, marcado) e um upload.
