### ISSUE TITLE
US94 - Curvas de crescimento

### ISSUE THREAD

**Issue by sconetto** [fga-gpp-mds/2018.1-Dr-Down#223]
Eu como usuário (equipe de saúde) gostaria de ter as curvas de evolução e crescimento do meu paciente para ajudar no diagnóstico e demais tarefas envolvidas a fim de melhorar a percepção do paciente e meu atendimento.

Critérios de aceitação:
 - A lógica deve ser construído como microserviço
- O microserviço tem que ter endpoints para a lógica de verificação se o paciente está acima ou abaixo do ideal de acordo com os gráficos disponibizados na tese de doutorado sobre curvas de crescimento para SD.
- O microserviço deve disponibilizar de um vetor de pontos para plotar o gráfico, esse vetor deve ser das  partes inferiores e superiores do gráfico que diz respeito a área ideal que o paciente deve se encontrar.
 - Deve ser testado

**Comment by VictorArnaud** [comment]
Fiz só algumas modificações nos critérios de aceitação
