### ISSUE TITLE
TS102 - Integração contínua do micro serviço

### ISSUE THREAD

**Issue by marimendes** [fga-gpp-mds/2018.1-Dr-Down#240]

**Comment by marimendes** [comment]
O micro serviço está pronto, basta fazer a integração e consumi-ló

**Comment by sconetto** [comment]
Link para o Travis CI do microserviço: https://travis-ci.org/Dr-Down/sdcurve/

**Comment by sconetto** [comment]
Link do Docker Hub com a imagem do serviço: https://hub.docker.com/r/sconetto/sdcurve/

**Comment by sconetto** [comment]
Link para a ferramenta de análise estática (Codacy): https://app.codacy.com/app/sconetto-joao/sdcurve/dashboard

**Comment by marimendes** [comment]
Ignora kkkk vi que tem pr no outro repositório :v:
