### ISSUE TITLE
TS115 - Revisão dos ambientes 

### ISSUE THREAD

**Issue by marimendes** [fga-gpp-mds/2018.1-Dr-Down#271]
Revisão dos scripts de deploy
Configuração do e-mail

**Comment by sconetto** [comment]
As revisões já foram feitas e a configuração também, mas agora tropeçamos num outro defeito:
https://github.com/pydanny/cookiecutter-django/issues/1678

Uma issue foi aberta para tentar solucionar

**Comment by sconetto** [comment]
A issue ficará fechada devido aos critérios terem sido atendidos, uma nova será criada para atacar o defeito que foi encontrado durante a execução desta.
