### ISSUE TITLE
US121 - Notificação por e-mail

### ISSUE THREAD

**Issue by marimendes** [fga-gpp-mds/2018.1-Dr-Down#289]
Eu, como paciente/parente, gostaria de receber notificações por e-mail de quando o status da minha consulta for alterado.

Eu, como paciente/parente, gostaria de receber notificações por e-mail de eventos criados, modificados ou cancelado.

Eu, como paciente/parente, gostaria de receber notificações por e-mail do status da minha checklist.

**Comment by ebmm01** [comment]
Comportamento funcionando conforme conversado com EPS.
