### ISSUE TITLE
TS131 - Correção da aba curvas de crescimento 

### ISSUE THREAD

**Issue by marimendes** [fga-gpp-mds/2018.1-Dr-Down#307]
**curvas de crescimento**

- [ ] tradução dos campos
- [ ] texto de ajuda ("Equivalente...")
- [ ] tirar o Na
- [ ] texto do perímetro cefálico (faltou especificar que deve ser em meses)
- [ ] Os campos de curvas estão com o frontend diferente do frontend da página de editar informações por exemplo. (Os campos de data e texto são mais arrendadinhos)

**Comment by ebmm01** [comment]
Testado e funcionando na homologação
