### ISSUE TITLE
TS133 - Prontuário

### ISSUE THREAD

**Issue by marimendes** [fga-gpp-mds/2018.1-Dr-Down#309]
- [x] Ao criar algo está redirecionando para a aba errada 

**Prescrição:**
- [x] modificar de remédio para prescrição no titulo formulário

 **Queixa formulário:**
- [x] Hora da queixa aumentar o campo

**Formulário risco**
 - [x] Os campos estão bagunçado

**Comment by ebmm01** [comment]
Testado e funcionando  no Homolog
