### ISSUE TITLE
TS134 - Eventos

### ISSUE THREAD

**Issue by marimendes** [fga-gpp-mds/2018.1-Dr-Down#310]
- [x] Colocar valor mínimo > 0

**Notificações**
- [x] No caso de um responśavel sem filhos, consultas está bugado (julio) e está aparecendo linha de cuidado
- [x] Redirecionamento no caso da linha de cuidado, quando logado como paciente

**Comment by joberthrogers18** [comment]
Confirmado no homolog, todas as funcionalidades implementadas funcionando corretamente.
