### ISSUE TITLE
TS142 - Documento de arquitetura

### ISSUE THREAD

**Issue by marimendes** [fga-gpp-mds/2018.1-Dr-Down#318]
- [x] Atualizar os componentes usados e não usados e todos os textos subsequentes da seção 2)
- [x] Adicionar uma parte na seção 2 para o SDCURVE explicando-o 
- [x] Atualizar imagem do diagrama de classes
- [x] Revisar o documento
- [x] Adicionar gráficos

**Comment by VictorArnaud** [comment]
Arquitetura:
![arquitetura](https://user-images.githubusercontent.com/14116020/41634143-ac392e20-7418-11e8-8cc4-d4f3bc9fd312.png)

Arquitetura Planejada:
![arquitetura_planejada](https://user-images.githubusercontent.com/14116020/41634137-a3b40162-7418-11e8-84c4-44cbd0410f35.png)

Arquitetura Definida:
![arquitetura_definida](https://user-images.githubusercontent.com/14116020/41634127-96fa4bde-7418-11e8-88eb-a57f056d2b41.png)
