### ISSUE TITLE
Marcar o churrasco top :D 

### ISSUE THREAD

**Issue by marimendes** [fga-gpp-mds/2018.1-Dr-Down#345]
Essa issue é de EXTREMA importância.
Precisamos decidir o local, o dia e o que levar. 

- [ ] Convencer a Gabriela e a Geovana irem. 
- [ ] Definir o que cada um vai levar.
- [x] Local 
- [x] Hora
- [x] Dia

**Comment by RochaCarla** [comment]
Se não fecharem essa issue, nem a nota de vcs eu lanço :P

**Comment by sconetto** [comment]
Definições:
Local: Casa do @sconetto
Dia: 07 de julho de 2018 (07/07/2018)
Hora: Começa às 10, sem hora pra acabar!

**Comment by marimendes** [comment]
A tarefa mais difícil será convencer a @gabiMSilva e a @GeovanaRamos

**Comment by RochaCarla** [comment]
@marimendes a nota delas vai ser condicionada à presença no evento! @gabiMSilva @GeovanaRamos ..
coloca as fotos evidenciando na issue :)
