### ISSUE TITLE
Elaborar o EVM

### ISSUE THREAD

**Issue by marimendes** [fga-gpp-mds/2018.1-Dr-Down#38]

**Comment by marimendes** [comment]
https://www.pmi.org/learning/library/earned-value-management-systems-analysis-8026 
https://www.projectsmart.co.uk/earned-value-management-explained.php
Esses links devem ajudar na elaboração da evm @sconetto :+1:

**Comment by marimendes** [comment]
https://codetiburon.com/earned-value-management-evm-agile-software-projects/ mais um :v:

**Comment by marimendes** [comment]
@RochaCarla O BAC (Total de despesas planejado) a gente faz do projeto todo ou por release? Ou a decisão é nossa?

**Comment by sconetto** [comment]
@marimendes essa issue não é a mesma da #50?
E estou usando essa fonte também http://www.hiflex.com.br/v1/gerenciamento-de-valor-agregado-evm-em-projetos-ageis/
