### ISSUE TITLE
US27 - Elaborar página de informação sobre síndrome de down

### ISSUE THREAD

**Issue by marimendes** [fga-gpp-mds/2018.1-Dr-Down#43]
Eu, como usuário, gostaria de ter acesso as informações sobre síndrome de down a fim de me manter informado.

**Comment by marimendes** [comment]
Utilizar as informações obtidas no TCC e pelo cliente. 

Outras fontes: http://www.movimentodown.org.br/sindrome-de-down/o-que-e/
http://www.fsdown.org.br/sobre-a-sindrome-de-down/o-que-e-sindrome-de-down/

**Comment by sconetto** [comment]
Issue fechada no merge #65
