### ISSUE TITLE
Feedback 01

### ISSUE THREAD

**Issue by RochaCarla** [fga-gpp-mds/2018.1-Dr-Down#46]
Pessoal,

alguns feedbacks do trabalho de vcs

- [x] Organização das issues está legal. Alguns pontos de melhoria: tem algumas issues sem descrição, e falta comentar as issues sobre a execução das mesmas

- [x] A documentaçao das sprints está ruim. Muito resumida, atrasada, não apresenta os indicadores, nem avaliação do scrum master. A falta de transparência no acompanhamento da metodologia adiciona mais um fator de risco no projeto, além de dificultar bastante vocês aplicarem as práticas ágeis corretamente. Scrum master deve dar maior prioridade a essa tarefa

- [x] Não achei documento sobre como a metodologia vai ser aplicada, nem quais são as principais atribuições dos papéis

- [x] Não encontrei o roadmap do projeto (EAP + Epicas). Outro ponto que aumenta o risco do projeto.  Por mais que o escopo seja alterado, esses artefatos evoluem com a evolução da visão do projeto.  A falta dele aumenta o risco, pois vocês não conseguem dessa forma planejar a curto prazo mas com o olhar a longo prazo

- [x] Roadmap dos papéis: falta um roadmap das tarefas dos principais papeis no projeto (scrum master, devops, arquitetura). Não achei tb issues associado a esses papeis (somente de devops). Outra evidencia que a falta de roadmap aumenta o risco do projeto

**Comment by marimendes** [comment]
Boa tarde professora, obrigada pelo feedback.

A primeira versão da EAP se encontra aqui: https://github.com/fga-gpp-mds/2018.1-Dr-Down/blob/support/sprint-02/docs/EAP.md

O roadmap também já está sendo feito.

As primeiras sprints serão refatoradas ainda nessa sprint, elas tiveram poucas informações porque ainda estávamos definindo as coisas e arrumando velocity e burndown.

**Comment by RochaCarla** [comment]
@marimendes valeu pelo retorno! 
Quanto ao cliente de vocês, vai ser o prof Sanderson mesmo. Podem marcar uma agenda fixa com ele..
Essa EAP está muito genérica, e não reflete valor de produto...Na proxima aula dou algumas sugestões

**Comment by marimendes** [comment]
Obrigada de novo professora. Iremos rever a EAP o quanto antes.

A descrição dos papeis se encontra nesta branhc que será mergeada: https://github.com/fga-gpp-mds/2018.1-Dr-Down/tree/support/TSxx-scrum-documentation

**Comment by marimendes** [comment]
Professora, tudo o que foi apontado aqui acredito que tenha sido resolvido na sprint passada! Aguardo o próximo feedback. :v:
