### ISSUE TITLE
DT39 - Refatorar o usuário base.

### ISSUE THREAD

**Issue by marimendes** [fga-gpp-mds/2018.1-Dr-Down#69]
Usuário base = aquele que será usado como base para os outros usuários. Os outros usuário serão herdados desse.

Divida técnica da sprint 02 - issues #27 #28 #29 

Adicionar campos que serão comuns entre os outros usuário.

**Comment by sconetto** [comment]
@joberthrogers18 @gabiMSilva https://github.com/pydanny/cookiecutter-django/issues/450

**Comment by sconetto** [comment]
https://docs.djangoproject.com/en/2.0/topics/auth/default/#topic-authorization
Repassem a todos esse link, talvez seja um bom caminho para grupos de autorização
