### ISSUE TITLE
TS48 - Configuração do Deploy Contínuo

### ISSUE THREAD

**Issue by sconetto** [fga-gpp-mds/2018.1-Dr-Down#83]
Criação e configuração de artefatos que vão possiblitar o deploy contínuo da aplicação Dr. Down.

**Comment by sconetto** [comment]
https://gitlab.com/lappis-unb/internal/docs

**Comment by sconetto** [comment]
```
$ export DOCKER_ID_USER
$ docker login (verificar com fazer o login via CI)
$ docker tag 20181drdown_django $DOCKER_ID_USER/drdown_django (verificar quais são os containers que vão precisar ser _tagados_ e _pushados_)
$ docker push $DOCKER_ID_USER/drdown_django
```

**Comment by sconetto** [comment]
@RochaCarla estamos com um impedimento, estamos sem um host para fazer os testes e continuar esse história do deploy contínuo, já pleitiei junto ao github aquele student pack que dá cupom ao digital ocean, mas infelizmente eles ainda necessitam de uma informação para pagamentos que os membros de EPS não tem (cartão de crédito internacional), tem como você ajudar a gente?

**Comment by VictorArnaud** [comment]
Microserviço de envio de emails: https://github.com/clevertech/email-service

**Comment by sconetto** [comment]
Essa _issue_ é legado e será executada em novas issues à se abrir posteriormente, dado este fato essa será fechada e ficará como histórico no repositório.
