### ISSUE TITLE
Olhar opções de ferramentas de grupo de conversa 

### ISSUE THREAD

**Issue by DanMke** [fga-gpp-mds/2018.1-Dr-Down#92]
olhar

- [ ] rocket.chat --> grupos de conversa

- [ ] hubot-natural -- fac? ajudante virtual ?

https://github.com/lappis-unb/minc-rouanet-bot 

- [ ] olhar app receituario medico -- chat medico/paciente

**Comment by marimendes** [comment]
Achei bem interessante, dei uma olhada e acho que mais pra frente podemos implementar pro projeto.

**Comment by marimendes** [comment]
@VictorArnaud @Diego-BF @sconetto

**Comment by sconetto** [comment]
https://github.com/fga-gpp-mds/2017.2-Receituario-Medico

**Comment by VictorArnaud** [comment]
Galera vi a possibilidade de utilizar o Receituario-Medico com um dos integrantes que criou o projeto, só que tem coisas que não tão funcionando muito bem, além de que ta bem acoplado ao projeto deles então vai dar bastante trabalho desacoplar, empacotar e inserir/adaptar no nosso. Logo vou fazer uma pesquisa mais a fundo de possibilidades para esse caso e colocar aqui para a equipe toda avaliar

**Comment by VictorArnaud** [comment]
1) https://github.com/Bearle/django-private-chat

Achei o layout bem interessante, vou testar assim que possível ver como se integra e se ta tudo funcionando, mas acho que é uma boa opção

**Comment by VictorArnaud** [comment]
2) https://github.com/CleitonDeLima/django-tawkto

Achei bem interessante também

**Comment by VictorArnaud** [comment]
https://developers.messagebird.com/start

**Comment by VictorArnaud** [comment]
https://github.com/jadolg/rocketchat_API

API do rocket.chat para python

**Comment by marimendes** [comment]
Foi decidido que não haverá mais chat, portanto estou fechando essa issue.
